version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "user_service"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  pgdata:
