version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=123456
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data
    command: redis-server --requirepass "123456"

volumes:
  redis_data:
